model:
  name: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
  api_base: "http://localhost:8000/v1"
  api_key: "dummy"

processing:
  temperature: 0.0
  max_tokens_summary: 1024
  max_tokens_classification: 1048
  start_index: 0
  early_break: 5
  inner_loop_break: 5
  show_resources: false
  print_prompts: false
  print_response: false
  print_progress: false
  use_progress_bar: false

output:
  path: "df_text_clas_server.csv"

logging:
  file: "processing.log"

