model:
  name: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
  api_base: "http://localhost:8000/v1"
  api_key: "dummy"

processing:
  temperature: 0.0
  max_tokens_summary: 8192
  max_tokens_classification: 8192
  start_index: 0
  early_break: null
  inner_loop_break: null
  log_resources: false
  log_prompts: false
  log_response: false
  log_progress: True
  use_progress_bar: True
  async_processing: True
  max_retries: 5
  max_concurrent_rows: 100

output:
  path: "df_text_clas_server.csv"

logging:
  file: "processing.log"
